name: Ejecutar notebook de análisis de acciones
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          python-version: "3.10"
          channel-priority: strict
          auto-update-conda: true
          activate-environment: final-stocks
          environment-file: environment.yml

      - name: Ejecutar notebook con papermill
        run: |
          papermill Final_Assignment-v2.ipynb output.ipynb
